on: [push, pull_request, workflow_dispatch]

jobs:

  build_windows:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: ./config/corne/windows
      archive_name: corne_windows

  build_mac:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: ./config/corne/mac
      archive_name: corne_mac

